src/Mimi.jl
This is a work in progress, not yet ready to be merged.
This makes all the generated types from the ``@defcomp`` macro parametric types, so that one can specify a type that should be used for any parameter or variable that is defined as a Number. The idea is that one can easily choose between say a ``Float64``, some kind of dual number or something entirely different as the type for numbers.
Things that still need to be done:
There are also at least two design questions that are not trivial:
- The current design will require a choice about the type to be used at the time of construction of the model object. In some ways that is not ideal, it would be better if one could create the structure of the model without making that choice, and then could specify the type when one runs the model. …
=> WIP: Parametric number type

doc/faq.md, src/Mimi.jl, src/references.jl, test/runtests.jl, test/test_references.jl
Here is the system for component references-- so that we can write, e.g.,
connectparameter(model, :MyComponent, :myparameter, :YourComponent, :yourparameter)
as
mycomponent[:myparameter] = yourcomponent[:yourparameter]
=> Add component references system

src/Mimi.jl, src/metainfo.jl, test/test_main.jl
@jrising and @FrankErrickson: This changes some fundamental things under the hood, but should not break any existing code that uses Mimi. I tried it with fund.jl, mimi-sneasy.jl, mimi-dice-2013.jl and mimi-rice-2010.jl and those all seem to work. I believe you both have code basis that use Mimi that I don't have access to, could you try to run those with the version of Mimi in this PR and let me know if there are any problems?
The major benefit for now is that one can redefine a component with this version without exiting the julia process. More medium/longterm this PR lays the foundation for a whole bunch of other improvements. Plus the code should be a fair bit easier to maintain because now less stuff is happening in the macro itself, which always was a pain to develop/debug.
Thanks!
=> Move type creation from macro to normal runtime phase

src/Mimi.jl, src/clock.jl
This is in preparation for a more general API overhaul. For now this should all be considered internal.
Eventually I want to pass a ``Clock`` object to the ``timestep`` function, and then components should use ``gettimestep`` to extract the current t at the top of their ``timestep`` function. Major benefit of such a design would be that we could later add bells and whistles to the ``Clock`` object without breaking the call signature for ``timestep``, i.e. we could add features without breaking old components.
@jrising could you briefly make sure this doesn't break any of your use cases? Right now this should be entirely non-breaking.
=> Add clock type and use in run method

src/Mimi.jl, src/metainfo.jl, test/runtests.jl, test/test_units.jl
This is the component-to-component part of the unit checking system.  You add new units like this:
```waterdemand = Parameter(index=[regions, time], units="1000 m^3")```
and when you call `connectparameter` with two components, it checks that the units match, allowing a special `any` unit that matches anything, but otherwise requiring that the units are the same or both missing.  I have all my calls like this through lines like:
```allocation[:waterdemand] = waterdemand[:totaldemand]```
This does not (1) handle any unit checking anywhere except for through `connectparameter` (and not the version of `connectparameter` that takes an already-added parameter as an argument, (2) have any logic for the `UnitedObject` that I mentioned before, nor (3) apply the unit logic to equations.
=> add unit handling and connection checking

NEWS.md, doc/tutorial.md, examples/01-onecomponent.jl, src/Mimi.jl, test/test_references.jl
This is breaking change. There are two specific changes: 1) the ``timestep`` function is renamed to ``run`` and 2) instead of passing the time index, I now pass a ``Clock`` instance from which one can extract the current timestep via the ``gettimestep`` function.
Motivation for 1) is that it always bugged me that the function name wasn't a verb. Plus, if we ever change it then now, while we still roughly know who is using this. If you don't like the name, speak now or never ;)
Motivation for 2) is that we can later on pass more information into components without a need to update the call signature again by adding more fields to the ``Clock`` structure.
@jrising, @frankerrickson, any review would be appreciated! I plan to merge this maybe end of the week if I don't hear back. Right now I …
=> Rename timestep to run and pass Clock instead of timestep

test/REQUIRE, test/test_dependencies.jl
@ckingdon95 I've replaced the ``InfoZIP.unzip`` method with something custom. The InfoZIP was just unbelievably buggy on Windows... This is just FYI, no need to do anything on your end.
=> Fix unzip windows

src/Mimi.jl
Both of these should make no difference for normal usage, but make things more convenient for a couple of use cases.  There are two changes:
* Combined the two `addcomponent` calls.  The only advantage for this is if you have another function which is calling `addcomponent` which could take a `name` parameter, and then can just pass it in.
* If the model uses a type other than `Float64`, it automatically does conversions.  So you can always call `setparameter` the same way, no matter what the number type of the model is.
=> Add conveniences for OptiMimi

.travis.yml, src/Mimi.jl, test/runtests.jl, test/test_dependencies.jl
Removed the test_dependencies.jl test from runtests, but added it to the travis script.
Note that I cleaned out the `if [ -f test/runtests.jl ]; then` part of the travis script.  If runtests.jl isn't there, that's a pretty big problem too.
=> Skip model dependencies except on Travis CI

src/Mimi.jl
Instance names of components in a model can never be resolved in the global meta component namespace, this looks things up with the component type name instead, which is the right case.
@ckingdon95 does my PR here look right to you? We should also add a test that catches this error.
=> Fix bug that surfaced in setleftoverparameters

examples/tutorial/01-one-region-model/one-region-model.jl, examples/tutorial/02-two-region-model/two-region-model.jl
Change tutorial `:time` index definitions from `[2015:5:2110]` to `collect(2015:5:2110)`. With this change, the examples in the `oneregion` and `multiregion` tutorials work.
Addresses #2
=> collect() :time indices in tutorial

src/mimi-core.jl
The `convert(Array{T}, x)` call is prone to alias to x in Julia 0.6.  What we really want to do (and here just do explicitly) is allocate a new array of type T to ensure that it is the right type.
=> Forces conversion to model type

wip/export_all.jl
Added macro `@import_all` in wip folder.
=> Macro to aid in debugging by importing all symbols from a package.

src/Mimi.jl, src/components/connector.jl, src/core/build.jl, src/core/connections.jl, src/core/defcomp.jl, src/core/defs.jl, src/core/dimensions.jl, src/core/instances.jl, src/core/model.jl, src/core/time.jl, src/core/types.jl, src/utils/getdataframe.jl, src/utils/misc.jl, src/utils/plotting.jl, test/runtests.jl, test/test_connectorcomp.jl, test/test_getdataframe.jl, test/test_marginal_models.jl, test/test_model_structure.jl, test/test_timesteps.jl, test/test_tools.jl, test/test_variables_model_instance.jl
Sorry for another big PR. Almost all tests pass except for a couple of known problems, e.g., the use of `t::Timestep` as final arg to `run_timestep` remains broken, but barely...
- Reinstated include of plotting.jl since Plots.jl (once again) doesn't break pre-compile
- Created TimestepArray and simplified many functions that were duplicated for TimestepVector/TimestepMatrix, or had to branch on type. Now supports > 2 dimensions.
- Eliminated AbstractTimestepMatrix
- TimestepVector/TimestepMatrix now defined as consts that parameterize TimestepArray with N=1 or N=2, respectively.
- Reimplemented build function to instantiate all vars first so the storage could be referenced directly by connected params.
- Eliminated use of Ref types
- Revised @defcomp to generate functions named …
=> Performance improvements, revisions to tests, and more.

src/mcs/montecarlo.jl
@rjplevin this was the directory bug I was mentioning. Currently folders for multiple models get nested within one another because 'output_dir' is repeatedly being reused
=> Fix MCS output directory nesting

src/core/connections.jl, src/core/model.jl
This PR adds methods to `set_external_param!` so that it has functionality to call `set_external_scalar_param!` and `set_external_array_param!`.  This allowed simplification of `set_leftover_params!`. 
Issue:  mimi-page-2009.jl Issue 2: setdistinctparameter()
**Outstanding Issues:** do we need to `decache(m)` after `set_external_param!`
=> Add methods to set_external_param!

src/core/build.jl, src/core/connections.jl, src/core/instances.jl, src/core/model.jl, src/core/types.jl, test/mcs/test_defmcs.jl
...and eliminated redundant `Scalar` type in favor of identically-defined `ScalarModelParameter`.
=> Fixed MCS processing 

src/core/defs.jl
found that this wasn't defined while working on a 3-dimensional component, so it would error when trying to copy the external parameters.
=> Adds copy function for generic TimestepArray

src/core/build.jl, src/core/connections.jl, src/core/defcomp.jl, src/core/defs.jl
If a default was given as an Int, it would override the declaration of Parameter type, confounding a subsequent MCS which tries to store a float into this location.
=> Fixed bug in processing declared type of model Parameters.

src/mcs/montecarlo.jl
I think this was a bug? Not sure why it wasn't always causing problems, but I just ran into an error that said "Can't convert to a Symbol", and this fixes it
=> Fix random variable name key

src/core/defcomp.jl, src/core/defs.jl, test/test_parametertypes.jl
- Default values must have the same number of dimensions as the parameter (via the indexes=[...] option or lack thereof)
- Default values and other values are converted to the parameter's declared type (or lacking a declaration, to the Model's number_type) when set.
- Added tests for correct treatment of "number_type" applied to params of unspecified types
=> Revised treatment of default parameter values and parameter types.

src/core/defs.jl, test/test_model_structure.jl
Add a check and corresponding error if `add_comp!` is called before a time index is set.  Per issue #304
=> add_comp! check for time dim

src/core/defs.jl, src/core/model.jl, test/runtests.jl, test/test_replace_comp.jl
Address issue #289 , with optional bool argument `reconnect`.
If reconnect==false, same behavior as before.
If reconnect==true, then replace_comp! only deletes the old component from md.comp_defs, and does not delete the internal or external parameter connections that the component belongs to.
It performs the following checks (in the case of reconnect==true):
- it checks that the new component definition has any parameter names that are present in any incoming internal parameter connections, and checks that the dimensions and datatype are the same. Question: should all of the datum fields need to match? Like units and description?
- it checks that the new component definition has any variable names that are present in any outgoing internal parameter connections, and checks that the …
=> WIP replace_comp!

src/mcs/mcs_types.jl, test/mcs/test_empirical.jl
I removed the type restrictions on `dist_rvs` and this seems to have solved the original problem. Not sure we have enough tests to verify that it doesn't create other problems...
Issue #312
=> Enable automatic storage of EmpiricalDistribution values

docs/src/internals/montecarlo.md, src/mcs/lhs.jl, src/mcs/mcs_types.jl, src/mcs/montecarlo.jl, test/mcs/test_defmcs.jl, test/mcs/test_empirical.jl
Some of these changes reflect my understanding of what the `dist_rvs` and the `rvdict` fields of a MonteCarloSimulation object are meant to represent.
from conversation on PR #315 : 
Is it that dist_rvs should be considered immutable, preserving the original distributional definitions, whereas rvdict is the one that gets updated to SampleStores and is used for getting trials? @rjplevin is this how we should be thinking of these two fields?
=> WIP generate_trials! changes

src/core/build.jl, src/core/connections.jl, src/core/defs.jl, src/core/types.jl, test/test_components.jl, test/test_metainfo.jl, test/test_metainfo_variabletimestep.jl, test/test_model_structure.jl, test/test_parametertypes.jl
issue #306 
Changes:
- Component definitions have their first and last values set to `nothing`, unless calls to `add_comp!` explicitly give values
- Component instances get their first and last values set to the first and last values from the component definitions if they are not `nothing`, or from the model's time index at that point
- This involved modifying the ComponentInstance constructor to explicitly take first and last values
- additional internal helper functions were added:
```
first_period(md::ModelDef, comp_def::ComponentDef) = first_period(comp_def) == nothing ? time_labels(md)[1] : first_period(comp_def)
last_period(md::ModelDef, comp_def::ComponentDef) = last_period(comp_def) == nothing ? time_labels(md)[end] : last_period(comp_def)
```
- most internal uses of the functions …
=> WIP component run periods

docs/src/integrationguide.md, docs/src/reference.md, docs/src/userguide.md, src/Mimi.jl, src/core/time.jl, test/test_timesteps.jl
@rjplevin  @ckingdon95 Note that if `t` is your last timestep i.e. `is_last(t) == true`, and `t_next = next_timestep(t)`, the time associated with `t_next` will always be `gettime(t) + 1`, *even for variable timesteps* where preceding steps might have been greater than 1.  This was an assumption we decided to make when dealing with how to deal with the final step, and I still think it holds well here, but wanted to mention it.  We really shouldn't be calling `is_time` on that `t_next` ... but I think it's fine as it is.  One idea would be to throw a warning if we do that, but could that check could add overhead.
=> Add is_timestep and is_time functions

.travis.yml, benchmark/benchmarks.jl, benchmark/getindex.jl, src/components/connector.jl, src/core/build.jl, src/core/connections.jl, src/core/defs.jl, src/core/time.jl, src/utils/getdataframe.jl, test/runtests.jl, test/test_connectorcomp.jl, test/test_datum_storage.jl, test/test_getdataframe.jl, test/test_model_structure_variabletimestep.jl, test/test_plotting.jl, test/test_timesteparrays.jl, test/test_timesteps.jl
This changes the array allocation for datum in components whose time dimensions are shorter than the model's time dimension. Now, TimestepArrays are allocated for the full length of the model's time index, and any cells before or after the component's first or last timestep values are padded with `missing` values. Addresses issue #321 
To do/questions:
=> WIP Datum Storage

.travis.yml
Due to upcoming breaking changes in Documenter. This makes sure that the doc builds do not start failing when 0.20 lands in METADATA. [See this thread on Discourse for more information.](https://discourse.julialang.org/t/psa-documenter-jl-breaking-changes-version-capping/16431) 
Ref: JuliaDocs/Documenter.jl#861
=> Cap Documenter to v0.19

REQUIRE, src/core/build.jl, src/core/defcomp.jl, src/core/defs.jl, src/core/types.jl, src/utils/misc.jl, test/test_components.jl, test/test_dimensions.jl
I've restored support for dimensions given simply as an integer, and all the tests pass, but I haven't tested it on a "real" model that uses this feature. 
@lrennels, would you be willing to test this on the model that illuminated the problem? If that works, and all other tests pass, I think we're good to go. (DONE, works on fund)
=> Anonymous dimensions

src/components/connector.jl, src/core/connections.jl, src/core/time.jl, test/test_timesteparrays.jl
- Allows for backup data to contain `missing` values by adding the Union{Missing, T} type where the array is instantiated
- Allows ConnectorComps to access missing values and pass them through
=> Support `missing` backup data

test/test_dependencies.jl
Fixes #377 
- need to update `fund` path once the `1.0` branch is merged
=> Update dependency paths

docs/src/userguide.md
As of now, if a `Variable` or `Parameter` has `time` as one of its indices, `time` **must** be listed first.  For example, `R = Variable(index = [segments, time, 5])` is not allowed, but `R = Variable(index = [segments, time 5])` is allowed. 
This PR makes the documentation about this invariant more clear, and I recommend we also add a better error message somewhere to make it easier to diagnose.  NOTE: do we want this to be an invariant or should we look into allowing the alternative?
=> WIP Clarify Docs on `time` Index ordering

src/mcs/montecarlo.jl
This PR fixes the MCS bug that did not increment `models_to_run` when a model, or vector of models, were passed to `run_mcs`.  It also augments the set of `run_mcs` methods to be comprehensive about `trials::Int` and `trials::Union{Int, Vector{Int}, AbstractRange{Int}}`.
=> Mcs bugfix

src/Mimi.jl, src/core/connections.jl, src/core/defcomp.jl, src/core/defs.jl, src/core/model.jl, src/core/types.jl, test/test_components.jl, test/test_main.jl, test/test_main_variabletimestep.jl, test/test_metainfo.jl, test/test_metainfo_variabletimestep.jl
- Eliminated global dict of component defs
- Fixed uses of eval to avoid precompilation issues
=> Eliminate global comp dict

docs/src/internals/montecarlo.md, src/mcs/montecarlo.jl
Change the `generate_trials` keyword argument `filename` default to `nothing` instead of `""`.  Addresses Issue #444.
=> Make generate_trials filename kwarg default to nothing

docs/src/tutorials/tutorial_2.md, docs/src/tutorials/tutorial_4.md
Following up on the conversations with Frank (https://forum.mimiframework.org/t/speed-of-mimi-monte-carlo-and-some-other-issues/38/11) I used some of the examples that @ckingdon95 wrote to built out Tutorial 4, hopefully clarifying the use-case of post-trial functions a bit.  This is. WIP, and I could use any input from @rjplevin and @ckingdon95 on how you think this can be cleaned up or clarified.  When @davidanthoff is back we can also have a discussion with Frank about it, but I wanted to get something added while it's on my mind.
Addresses #449
=> Add more post-trial functions to tutorial 4

src/core/build.jl
The `run` function for a normal Mimi model has `ntimesteps` as a keyword argument.
The `run` function for a MarginalModel had it not as a keyword argument. I'm guessing we should add in this semicolon so that it's the same type of option for running a MarginalModel. Thoughts?
=> Make ntimesteps a keyword arg for run(MarginalModel)

src/core/defs.jl, src/mcs/defmcs.jl, src/mcs/lhs.jl, src/mcs/mcs_types.jl, src/mcs/montecarlo.jl, src/mcs/sobol.jl, test/mcs/test_defmcs.jl
- Added methods to manipulate a `Simulation` instance
- Eliminated `sim.dist_rvs`
- Changed uses of `sim.dist_rvs` to call `values(sim.rvdict)`
See also my comments in #474
=> Simulation update funcs

src/core/model.jl
=> Add "show" method for Model

docs/src/userguide.md, src/explorer/buildspecs.jl, src/explorer/explore.jl, test/test_explorer.jl
=> Make single plots static not interactive

docs/src/tutorials/tutorial_1.md, docs/src/tutorials/tutorial_3.md, docs/src/userguide.md, src/explorer/explore.jl, test/test_explorer.jl
=> Change name of explore method for single plot

src/core/defs.jl, src/core/types.jl
This is a partial fix for module lookup problem that might suffice for the workshop.
It still won't handle nested modules, but we can deal with that next...
=> module lookup problem 

src/core/defs.jl, test/test_dimensions.jl, test/test_model_structure.jl, test/test_parametertypes.jl, test/test_replace_comp.jl, test/test_timesteps.jl
=> Remove some warnings from Mimi

src/mcs/mcs_types.jl
Plus `set_payload!` and `payload` methods.
=> Added support for opaque "payload" to be attached to Simulation

src/core/model.jl
@rjplevin could you do a quick review? I'd like to merge this today so that I have it for Wed. This does two things: a) it generally reduces output (the default in Jupyter is just way too much right now), and it tweaks what exactly is shown a bit.
=> Change the show method for Model

src/core/time.jl, test/runtests.jl, test/test_broadcast.jl
Fix bug in dotview() for timesteps and added preliminary example sent by James as test/test_broadcast.jl (not fully wired into testing system yet...)
=> Fix bug in dotview() for timesteps

.travis.yml, appveyor.yml
A release candidate was just released, so we can start testing on 1.2 regularly.
=> Add julia 1.2 to CI config

src/mcs/defmcs.jl, src/mcs/mcs_types.jl
Made it possible to call `sim = Simulation()` and use the new API to populate `sim`.
=> Add support for creating an empty Simulation

src/core/build.jl, src/core/model.jl, src/mcs/mcs_types.jl, src/mcs/montecarlo.jl, src/utils/getdataframe.jl, test/mcs/runtests.jl, test/mcs/test_marginalmodel.jl
These changes allow `MarginalModels` in a simulation instance's list of models. Previously, a `MarginalModel` `mm` would be "flattened" into two models `mm.base` and `mm.marginal` in the list of models. Now, if a user provides a MarginalModel to the `run` function, then accessing the list of models from a simulation instance will yield the exact same list of models and/or MarginalModels. 
This functionality is demonstrated in a new test file: "test/mcs/test_marginalmodels.jl".
=> WIP Support for MarginalModels in running simulations

docs/src/internals/montecarlo.md, docs/src/tutorials/tutorial_4.md, src/mcs/defmcs.jl
=> remove use of camelCase

docs/src/internals/montecarlo.md, docs/src/tutorials/tutorial_4.md, src/Mimi.jl, src/mcs/mcs_types.jl, test/mcs/test_defmcs.jl
This PR handles Issue #572.
Remove the `getindex` method for `SimulationInstance`and replace it with `getdataframe`.  Users will be able to use `getdataframe` to access results of a simulation while we do some thinking on what type we'd like `getindex` to return and how to handle the multidimensionality of scenarios etc.
=> Change getindex to getdataframe for sim_inst

src/core/build.jl, src/core/connections.jl, src/core/defcomposite.jl, src/core/defs.jl, src/core/types/defs.jl
Stopped exporting connected params, and added a call to the new function `propagate_params!()` to the code emitted by `@defcomposite`.
=> Fix param exports

docs/src/integrationguide.md, docs/src/userguide.md, src/core/defs.jl, src/core/instances.jl, src/core/model.jl, test/test_components.jl, test/test_datum_storage.jl, test/test_dimensions.jl, test/test_getdataframe.jl, test/test_model_structure_variabletimestep.jl, test/test_parametertypes.jl
=> Remove first and last keyword arguments

src/core/instances.jl, src/core/time.jl, src/core/types/instances.jl, test/test_dimensions.jl
Issue #538 
The `DimValueDict` previously held vectors of Ints for each dimension (keyed by a Symbol for the name of the dimension). Now, I've changed it so that the `:time` entry in this dictionary holds a vector of `AbstractTimestep`'s, so that calls to `d.time` in the `run_timestep` functions return timesteps that can be used for indexing into parameters and variables. There is only one place in the code where a `DimValueDict` object is constructed, and that is in the `run` function so that it can be passed to the `run_timestep` function.
Questions:
1. What I've implemented here was to modify the constructor of a `DimValueDict` to also take in the `Clock` object from which the `:time` vector of timesteps is created and stored in the dictionary (instead of a vector of Ints). …
=> Make d.time return AbstractTimesteps

src/core/defs.jl, src/core/model.jl, src/core/types/time.jl, test/test_dimensions.jl
=> Add variable_dimensions methods

test/runtests.jl
=> Add @time to all tests

src/core/connections.jl
#646 This PR fixes a bug in the `add_connector_comps!` function on master, where we have currently disabled functionality surrounding components with different lengths ... but this is a bug we will want to track and fix anyways unless we remove the function all together.  I'd suggest merging this fix for now.
=> Fix bug in add_connector_comps on master

src/core/connections.jl, test/test_parametertypes.jl
@jrising found this bug, more info on this forum post:
https://forum.mimiframework.org/t/array-parameter-setting-fails-with-int64-parameter-type/113
I added a line to the test file which now passes, but represents what previously would have errored.
=> Fix parameter type bug for non-time arrays

src/core/time_arrays.jl
This PR addresses #690, and improves the error message for the deprecation warning associated with integer indexing. Since the Stacktrace will change in each call, the improvement for now prints out the `stacktrace()` stack frame line by line instead of as a text block, ie. the following.
The component printout could still be quite long, however, but at least printed nicely.
```
┌ Warning: Indexing with getindex into a TimestepArray with Integer(s) is deprecated, please index with a TimestepIndex(index::Int) instead ie. instead of t[2] use t[TimestepIndex(2)]
│  
│ _get_stacktrace_string() at time_arrays.jl:62
│ _throw_int_getindex_depwarning at time_arrays.jl:71 [inlined]
│ getindex(::TimestepArray{FixedTimestep{2000,1,LAST} where LAST,Int64,1,1}, ::Int64) at time_arrays.jl:209
│ …
```
=> Improve int indexing depwarn msg

src/core/paths.jl, test/test_composite.jl
#689 
The problem was that `tail(comp_path)` returns not just the last element, it returns everything but the head. But what we want here is just the last element.
=> fix `_fix_comp_path!` for internal connections

docs/src/internals/structures_3_instances.md, src/core/build.jl, src/core/instances.jl, src/core/types/instances.jl, test/test_composite.jl
#677 
Currently we have implemented the methods and constructors needed to access parameters and variables in the top level composite components of a model with a call like
```
m[:top, :par_name
```
next steps are to add more comprehensive testing and think about corner cases like renaming.  also, do we want to be able to use this syntax for lower levels i.e. if `:B` is a child composite component of `:top` but not in the `comps_dict` of `m.mi`, should we be able to do 
```
m[:B, :par name]
```
=> Datum access

examples/compositecomp-model.jl, src/core/model.jl, test/runtests.jl, test/test_explorer_compositecomp.jl
Make small changes to allow a call to `explore(m)` on a model that contains composite components.  For now this will only display the namespaces of the top level components, and will not dive into the sub-components of a composite component.
#711
=> Explorer for Composite Components

src/core/connections.jl, src/core/defs.jl, src/core/model.jl, src/core/references.jl, test/test_references.jl
=> remove use of ComponentPaths as arguments in any user-facing functions

.github/workflows/dependencytest-workflow.yml, .github/workflows/jlpkgbutler-ci-master-workflow.yml, .github/workflows/jlpkgbutler-ci-pr-workflow.yml, Project.toml, docs/src/tutorials/tutorial_2.md, docs/src/tutorials/tutorial_3.md, docs/src/tutorials/tutorial_4.md, docs/src/tutorials/tutorial_5.md, test/test_components.jl, test/test_model_structure_variabletimestep.jl, test/test_timesteparrays.jl
=> Remove support of  1.2 and 1.3

src/core/defcomp.jl, src/core/model.jl, src/core/time.jl, src/core/time_arrays.jl, src/mcs/mcs_types.jl
This deprecation warning needs to be an error for v1.0.0, I noticed this when working on PAGE.
=> Change deprecation warning to error for sim instance access methods

docs/make.jl, docs/src/howto/howto_3.md, docs/src/howto/howto_main.md, docs/src/tutorials/tutorial_5.md, docs/src/tutorials/tutorial_main.md
@ckingdon95 so I realized that in my SA focus I really skipped over summarizing the SA functionality as both Monte Carlo simulation _and_ sensitivity analysis, which is actually quite misleading.  Should be fixed here!
=> Fix Monte Carlo docs

src/core/build.jl, src/core/model.jl, src/mcs/montecarlo.jl, test/test_components.jl, test/test_composite.jl, test/test_main.jl, test/test_main_variabletimestep.jl, test/test_model_structure.jl, test/test_model_structure_variabletimestep.jl, test/test_parametertypes.jl
The `build` function we previously had in the codebase doesn't return anything, but instead just modifies the model that is passed. So as a mutating function, it should really be named `build!`. First commit in this PR here makes that rename. I think that should be safe, given that this is an internal function.
The second commit then adds a `build` function that returns a model instance from a `Model`, but doesn't modify the `Model` itself. That is essentially what is documented in https://www.mimiframework.org/Mimi.jl/stable/howto_advanced/howto_adv_buildinit/#The-Internal-'build'-Function-and-Model-Instances-1, but not implemented currently.
This is a first step to address https://github.com/mimiframework/Mimi.jl/issues/753. What we then still need is an `update_param!` that works …
=> Cleanup build

src/core/defcomp.jl, test/test_parametertypes.jl
=> Remove eval from defcomp macro

src/core/connections.jl, test/test_main.jl
Fixes #753.
Before we merge this I'm going to test this with one of our paper replication codes. Also needs a test.
=> Add update_param! for a model instance

docs/src/ref/ref_API.md, src/Mimi.jl, src/core/defs.jl, src/core/model.jl, test/runtests.jl, test/test_delete.jl
#752 
Two additions in this PR:
1. This adds `delete_unbound_comp_params::Bool=false` keyword argument to the `delete!` function, which when set to true then deletes all external parameters that were only connected to the deleted component. 
2. I also created a new function `delete_param!(m, external_param_name, delete_connections=true)` for removing parameters from a model's list of external parameters.
To discuss:
- kwarg name: I went with the verbose `delete_unbound_comp_params` for now, which is definitely not perfect. The reason I'm feeling averse to `deep` or `recursive` is that it doesn't delete _all_ parameters associated with this component, only the ones not connected to any other components.
- in order to add this functionality, I had to change the function signature to only …
=> add `delete_unbound_comp_params` kwarg to `delete!`

src/core/defs.jl, test/test_delete.jl
when `deep=true` the ExternalParameterConnections for parameters that aren't being delete still need to be removed for the deleted component
=> fix ExternalParameterConnection bug in delete!

README.md, src/core/build.jl, src/core/connections.jl, src/core/defcomp.jl, src/core/defcomposite.jl, src/core/defs.jl, src/core/references.jl, src/utils/getdataframe.jl, test/runtests.jl, test/test_components_ordering.jl, test/test_composite_parameters.jl, test/test_num_components.jl
Hello!
My name is Jordan, and I'm new on this project. I met with @davidanthoff on Monday and he set me loose on the issue stack.
Edit: Here, I fixed a few grammatical issues, then set up a test to improve code coverage. I intended this mostly as an introduction and a hands-on way to begin to familiarize myself with Mimi's code.
=> Standardize error message grammar, add test for bad composite parameters, fix a few other grammar things

src/core/connections.jl, src/core/model.jl
- We need to add the (deprecated) keyword argument `update_timesteps` to `update_params!` so that it throws a warning instead of an error 
- `update_param!` on a model definition needs to use `copyto!`, otherwise we are breaking the connection between the model instance's component instance parameters (they use views for their TimestepArray data) and the model instance's model def's external parameters
https://forum.mimiframework.org/t/using-mimiiwg-jl/158
=> Update timesteps bugfix

docs/make.jl, docs/src/howto/howto_4.md, docs/src/howto/howto_5.md, docs/src/howto/howto_6.md, docs/src/howto/howto_7.md, docs/src/howto/howto_main.md, docs/src/ref/ref_structures_definitions.md, docs/src/tutorials/tutorial_3.md, src/core/build.jl, src/core/connections.jl, src/core/defs.jl, src/core/dimensions.jl, src/core/model.jl, src/core/types/defs.jl, test/runtests.jl, test/test_components.jl, test/test_dimensions.jl, test/test_firstlast.jl, test/test_model_structure.jl, test/test_parametertypes.jl
=> Time Dimension Work

docs/src/internals/structure.md, docs/src/tutorials/tutorial_3.md, src/Mimi.jl, src/components/README.md, src/components/multiplier.jl, src/core/defcomp.jl, test/runtests.jl, test/test_explorer_model.jl, test/test_multiplier.jl
This PR (1) adds a `multiplier` build in component to help with FUND-FAIR unit conversion and (2) per suggestion from #560 adds an `@allow_missing` wrapper to the `adder` and `multiplier` components, which also simplifies MimiFUND-MimiFAIR-Flat.
This means that if the multiplier component:
```
@defcomp multiplier begin
multiply  = Parameter(index=[time])
input       = Parameter(index=[time])
output      = Variable(index=[time])
function run_timestep(p, v, d, t)
v.output[t] = @allow_missing(p.input[t]) * p.multiply[t]
end
end
```
accesses a `missing` in `p.input[t]` it will not throw an error but just pass the value through.  Sometimes needing this can be avoid with setting a `first` and `last` for the `multiplier` component, but sometimes there's still an irritating off-by-one issue. For …
=> Add multiplier and allow_missing macro use

src/core/connections.jl
When we connect a variable from one component to the parameter of another, we only want to check if the units match _if both have been explicitly set_ .. ie. if the parameter has units "" by default, and the variable has units "millions" we don't want to error.
=> Only verify connection units if both are provided

contrib/test_all_models.jl, src/core/build.jl, src/core/connections.jl, test/test_dimensions.jl, wip/dims_testing.jl
This PR checks internal parameter connections for dimension mismatches between source variables and destination parameters.  Specifically we check that the length of each dimension in the parameter matches the length of the variable dimension in the corresponding position of the dimension list. In the future we can add checking of datatypes but for this PR we will isolate to dimensions and size issues.
TODO:
=> Check the dimensions when making internal parameter connections

src/core/connections.jl, test/test_connectorcomp.jl
This PR handles issue #865 
When a connector component is added using backup data, the parameter name for the backup data is a model parameter (unshared) that was getting overwritten if the destination component had the same destination parameter name as another.  This PR makes sure the added model parameter has a unique name.
Should we consider a check in `add_model_param!` to make sure a given parameter does not yet exist in the model, or is overwriting sometimes desired?
=> Unique Backup Parameter Names

src/core/time_arrays.jl
Fixes more performance regressions on Julia 1.7 and 1.8.
=> Remove some union splitting in time array clients

src/utils/getdataframe.jl
There are two commits here that are unrelated.
The one about the `deepcopy` I'm especially not 100% sure. But I think I followed all code paths, and I think previously the deep copy that was created originally was then actually never (except for the one case where I added a `deepcopy` returned to user, but was essentially always a temporary copy, in which case it seems unnecessary to me.
=> Improve performance

src/core/connections.jl, src/core/dimensions.jl, src/mcs/montecarlo.jl
This should fix some of the warnings on Julia 1.10
=> Remove some type parameters

src/core/dimensions.jl
Fixed minor type `anonymouse` - > `anonymous` (I do really like the sound of anonymouse though! :smile: )
=> Typo fix in dimensions.jl

src/core/instances.jl, src/core/model.jl
The `Base.run` function allows for an optional keyword argument `dim_keys`, which (as far as I can tell) allows the user to specify a subset of time periods which the model should be run for.
This keyword argument has the following type-declaration:
`Union{Nothing, Dict{Symbol, Vector{T} where T <: DimensionKeyTypes}}`
However, this type declaration doesn't recognize a supplied value of type `Dict{Symbol, Vector{Int64}}` as valid since 
`Dict{Symbol, Vector{Int64}} <: Dict{Symbol, Vector{T} where T <: DimensionKeyTypes}` returns a value of `false`, although this is presumably the intended use of the argument.
This PR fixes this by changing the type-declaration to:
`Union{Nothing, Dict{Symbol, Vector{T}} where T <: DimensionKeyTypes}`, which ensures that arguments of the type `Dict{Symbol, …
=> Fix small bug in Base.run for models and instances

.github/workflows/dependencytest-workflow.yml
Model testing is successful locally, but the current code tests the models on Julia 1.6 and 1.7 seem to have some test harness issues. At this point it seems reasonable to move this model testing to Julia 1.9 and 1.10, and noting we should add more models to this list to make the testing a bit more robust.
=> Update julia versions for dependency model tests

Project.toml
Given that 1.10 is the new LTS.
=> Bump minimal Julia version to 1.10
