.travis.yml, NEWS.md, REQUIRE, appveyor.yml, src/Mimi.jl, test/test_main.jl
@jrising unless you have a need for julia 0.3 compat, we could merge this.
=> Drop julia 0.3 support

doc/faq.md
A little FAQ, so other people don't try to build a new parameter type just to do multivariate parameters.
=> add FAQ on multivariate distributions

src/Mimi.jl, test/test_model_structure.jl
addresses issue #53 on anthofflab/Mimi.jl
=> WIP scalar parameter/variable connections

src/Mimi.jl, src/adder.jl, test/runtests.jl, test/test_adder.jl, test/test_addr.jl
=> WIP defcomp adder file

src/Mimi.jl
@davidanthoff I'm not entirely sure how to set reviewers but I should have fixed this issue in the last commit. I suppose we can connect at the meeting for future updates
=> WIP removed setbestguess

src/Mimi.jl, test/runtests.jl, test/test_model_structure.jl, test/test_num_components.jl
(created new up to date branch)
=> WIP finished test_num_components again

src/Mimi.jl, test/runtests.jl, test/test_getindex.jl
figured out a way to get variables of a given component given a modelinstance and using it for the getindex checks
will write a separate function in another pull request
=> WIP Get index check

src/Mimi.jl, test/runtests.jl, test/test_components_ordering.jl
broke previous commit to smaller commit and fixed bugs
=> WIP finished component ordering checks and tests

src/Mimi.jl, test/runtests.jl, test/test_variables_model_instance.jl
The variables function works using fieldnames but the function does not work on Nullable Instances
=> WIP Variables function taking in Model Instance (instead of Model itself)

.travis.yml, test/test_dependencies.jl
=> Add Mimi-RICE-2010.jl to dependency tests

src/Mimi.jl, src/metainfo.jl, src/mimi-core.jl, test/test_parameter_labels.jl
=> replaced all 'addparameter' occurences changed them to 'set_external_parameter'

src/mimi-core.jl
=> checklabels bug

src/Mimi.jl, src/mimi-core.jl, test/test_parametertypes.jl, test/test_timesteps.jl
Now external_parameter is the name of the external_parameter in the model (rather than storing the actual parameter)
=> changes ExternalParameterConnection

src/mimi-core.jl
Including this change (originally made to master) for Julia 6 release branch.
=> Cherry-pick change to force conversion of array types

src/metainfo.jl, src/timestep_arrays.jl, test/test_mult_getdataframe.jl
No need to really review this, tests pass, so this should be good. But I no longer want to just push things to ``master`` without giving you two a heads up and an ability to shout "wait with a merge". So I'll merge this as soon as one of you has approved the PR.
=> Fix remaining julia 0.6 deprecations

src/core/connections.jl, src/core/defs.jl
These are the last debugging commits to set_leftover_params! so that it runs smoothly with FUND.
=> Debug set_leftover_params! for FUND

README.md
Just a small update to the README to get the models list correct and the links working
=> Update README models list

REQUIRE
This small PR updates the REQUIRE file to include the necessary packages and get the builds passing again so that we can make sure future branches do not break the tests.
=> Update REQUIRE file

examples/tutorial/01-one-region-model/one-region-model-defaults.jl, src/core/build.jl, src/core/defcomp.jl, src/core/defs.jl, src/core/types.jl
Added ability to set Parameter defaults in defcomp.
=> Added support for default parameter values in @defcomp.

REQUIRE, test/mcs/test_defmcs.jl
Added N variable to test_defmcs.jl so tests pass
=> mcs3-fix-tests

src/mcs/EmpiricalDistribution.jl, src/mcs/mcs_types.jl, test/mcs/test_defmcs.jl, test/mcs/test_empirical.jl
Added more tests of the various callbacks in `run_mcs`.
=> More MCS tests

docs/src/userguide.md, examples/tutorial/02-two-region-model/emissions.jl
This PR improves the `init()` documentation per the discussion in #257.
=> Init() Documentation

src/core/types.jl
Just that... a blessedly tiny PR for a change!
=> Deleted duplicate definition in types.jl

docs/src/internals/structure.md, docs/src/userguide.md
This PR augments and corrects the internals documentation.
=> Internals Documentation

src/core/model.jl
=> Added delegation to disconnect_param!

src/mcs/lhs.jl, src/mcs/mcs_types.jl, src/mcs/montecarlo.jl, test/mcs/test_defmcs.jl
issue #313 
to do:
- add tests
=> WIP mcs generate_trials! specifications

REQUIRE, src/Mimi.jl, test/runtests.jl
... which is now working on 1.0.
=> Re-enable GraphPlot stuff

src/explorer/buildspecs.jl
=> Fix explorer interaction with missing values

.travis.yml, docs/src/internals/montecarlo.md, docs/src/tutorials/tutorial_1.md, docs/src/tutorials/tutorial_2.md, docs/src/tutorials/tutorial_3.md, docs/src/tutorials/tutorial_4.md, docs/src/tutorials/tutorial_main.md, docs/src/userguide.md, src/mcs/montecarlo.jl, test/mcs/test_defmcs.jl
=> WIP: Fix bugs in tutorials

docs/src/internals/montecarlo.md, docs/src/reference.md, docs/src/tutorials/tutorial_4.md, src/Mimi.jl, src/mcs/mcs.jl, src/mcs/montecarlo.jl, test/mcs/test_defmcs.jl, test/mcs/test_empirical.jl
Partial fix for `run_mcs` issue. @lrennels should take a look...
=> Separate set_models! from run_mcs

docs/src/tutorials/tutorial_1.md
This could be useful for users starting from a fresh installation of Julia (like me!)
=> added note on package installation

CONTRIBUTING.md, LICENSE, README.md, docs/make.jl, docs/src/installation.md, docs/src/tutorials/tutorial_1.md, docs/src/tutorials/tutorial_2.md, docs/src/tutorials/tutorial_3.md, docs/src/tutorials/tutorial_4.md, docs/src/tutorials/tutorial_main.md, docs/src/userguide.md
I'm just going to merge this, just wanted you all to know that I did this.
=> Update all URLs to new github org

docs/Project.toml, docs/make.jl
Set environment var JULIA_NO_LOCAL_PRETTY_URLS to anything to engage.
=> Make locally built docs work

src/core/defcomp.jl, test/test_components.jl
=> Handle doc string before run_timestep in @defcomp.

src/core/model.jl
=> Add error message to modelegate

test/dependencies/Manifest.toml
Hopefully this will fix the last remaining test problems.
=> Update dependency testing Manifest.toml

src/core/defs.jl
=> Add method for copying params with string or symbol type

src/core/time.jl, test/test_timesteparrays.jl
-  Added Base.dotview for TimestepArrays to fix broadcast assignment bug
- Added test of this feature
=> - Added Base.dotview method

src/core/model.jl
Not sure this is the final version, but hopefully we're converging!
=> Alternate `show` methods for `print` and for REPL results.

README.md, docs/src/index.md
https://forum.mimiframework.org/t/models-to-add-to-mimiframework-org/47
=> Add models to list of models using Mimi

contrib/test_all_models.jl
The comments at the beginning of the file should explain what it does. It just runs all the tests of all the models we have. Right now, almost all of them fail, but I haven't looked into why.
=> Add test_all_models.jl script

src/mcs/montecarlo.jl
=> Fix bug in _compute_output_dir

src/Mimi.jl, test/test_connectorcomp.jl, test/test_replace_comp.jl, test/test_variables_model_instance.jl
as per Issue #509. Added these, as needed, to imports in tests.
=> Remove exports of components, parameters, and variables

Project.toml, test/runtests.jl
This is in preparation for our move to GitHub Actions for CI.
=> Prepare tests for Github Actions

.github/workflows/dependencytest-workflow.yml, test/runtests.jl
Fixes #616.
I'll have to merge this right away to actually test whether it works.
=> Move dependency tests to separate workflow

src/core/time_arrays.jl, test/test_timesteps.jl
@ckingdon95 can you approve this it's jus little fixes I found while working on the remove deprecations branch
=> Fix small debug comment errors

src/core/model.jl, test/test_main.jl
#766 per @davidanthoff 's request
=> Add dim_keys for ModelInstance

src/core/references.jl, test/test_references.jl
@jrising would this work to fix your bug at #772  too?  I know it looks more verbose but it might be clearer in terms of code interpretability ...
=> Fix set_param for references

src/core/types/model.jl, src/explorer/explore.jl
@davidanthoff  here's a temporary constructor for @FrankErrickson ... should work for now can you approve?
=> Add temporary Model constructor

docs/src/index.md
Hi - the website for the documentation system is now maintained and updated at https://diataxis.fr.
I'm also doing some free workshops occasionally for open-source projects in the Python ecosystem, to help with their documentation. If you think that there might be interest in the Julia community, please let me know.
=> Update link to Diátaxis

src/explorer/buildmenu.jl, src/explorer/buildspecs.jl, test/test_explorer_model.jl
=> WIP Displaying Uncommon Types in Explorer Menu

src/mcs/montecarlo.jl
@jrising work in progress but I think this will solve https://forum.mimiframework.org/t/setting-a-distributions-over-large-dimensions-in-defsim/277/10
=> WIP Use Different Approach to Check for Broadcasting in Perturb Param

README.md
I saw this when I tried to contact you
=> Fix link to Lisa's website
